import { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Badge } from '../../../components/ui/Badge.jsx'
import { superadminService } from '../../../services/superadminService.js'
import {
  ResponsiveContainer,
  Tooltip as ChartTooltip,
  BarChart,
  Bar,
  CartesianGrid,
  XAxis,
  YAxis,
  PieChart,
  Pie,
  Cell,
} from 'recharts'
import {
  HiArrowPath,
  HiBuildingOffice,
  HiDocumentArrowDown,
  HiUsers,
  HiCurrencyDollar,
  HiCalendarDays,
  HiClock,
  HiTableCells,
  HiDocumentText,
  HiChevronDown,
  HiArrowDownTray
} from 'react-icons/hi2'
import toast from 'react-hot-toast'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import html2canvas from 'html2canvas'

const monthOrder = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
const weekOrder = ['SUN', 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT']

function toNumber(v) {
  const n = Number(v)
  return Number.isFinite(n) ? n : 0
}

function cap(v) {
  return `${String(v || '').charAt(0).toUpperCase()}${String(v || '').slice(1)}`
}

function formatDate(v) {
  if (!v) return '-'
  const d = new Date(v)
  if (Number.isNaN(d.getTime())) return '-'
  return d.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
}

function MetricTile({ icon, label, value, tone = 'slate' }) {
  const IconComponent = icon
  const tones = {
    slate: 'from-slate-900 to-slate-700',
    green: 'from-[#0F766E] to-[#0c6b64]',
    blue: 'from-blue-600 to-blue-500',
    emerald: 'from-emerald-600 to-emerald-500',
  }
  return (
    <div className="rounded-none border border-slate-200 bg-white p-4 shadow-sm">
      <div className="flex items-start justify-between">
        <div>
          <p className="text-[10px] font-semibold uppercase tracking-wider text-slate-500">{label}</p>
          <p className="mt-2 text-2xl font-bold text-slate-900">{value}</p>
        </div>
        <div className={`flex h-10 w-10 items-center justify-center rounded-none bg-gradient-to-r text-white shadow-sm ${tones[tone] || tones.slate}`}>
          <IconComponent className="h-5 w-5" />
        </div>
      </div>
    </div>
  )
}

// ─── Export Helpers ────────────────────────────────────────────────────────────

async function captureChart(ref) {
  if (!ref?.current) return null
  try {
    const canvas = await html2canvas(ref.current, {
      backgroundColor: '#ffffff',
      scale: 2,
      useCORS: true,
      logging: false,
    })
    return canvas.toDataURL('image/png')
  } catch {
    return null
  }
}

function addPageNumber(doc) {
  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 8,
      { align: 'center' },
    )
    doc.text(
      'Generated by HRIS SaaS Superadmin Dashboard',
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 4,
      { align: 'center' },
    )
  }
}

async function generatePDF({ stats, recentTransactions, recentlyRegistered, recentPlanExpired, chartRefs }) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageW = doc.internal.pageSize.getWidth()
  const margin = 14
  const now = new Date()
  const dateStr = now.toLocaleString('en-GB', {
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  })

  // ── Cover / Header ──────────────────────────────────────────────────────────
  // Teal header bar
  doc.setFillColor(15, 118, 110)
  doc.rect(0, 0, pageW, 38, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(20)

  doc.setFont('helvetica', 'bold')
  doc.text('REPORT', pageW / 2, 16, { align: 'center' })

  doc.setFontSize(8)
  doc.text(`Report Generated On: ${dateStr}`, pageW / 2, 31, { align: 'center' })

  let y = 46

  // ── A. Summary Cards ────────────────────────────────────────────────────────
  doc.setTextColor(15, 118, 110)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('A.  Dashboard Summary', margin, y)

  doc.setDrawColor(15, 118, 110)
  doc.setLineWidth(0.5)
  doc.line(margin, y + 2, pageW - margin, y + 2)
  y += 8

  const cards = [
    { label: 'Total Companies', value: String(stats.totalCompanies), color: [15, 118, 110] },
    { label: 'Active Companies', value: String(stats.activeCompanies), color: [30, 41, 59] },
    { label: 'Total Subscribers', value: String(stats.totalSubscribers), color: [37, 99, 235] },
    { label: 'Total Earnings', value: `$${Number(stats.totalEarnings).toLocaleString()}`, color: [5, 150, 105] },
  ]

  const cardW = (pageW - margin * 2 - 9) / 4
  cards.forEach((card, i) => {
    const x = margin + i * (cardW + 3)
    doc.setFillColor(...card.color)
    doc.roundedRect(x, y, cardW, 20, 2, 2, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(7)
    doc.setFont('helvetica', 'normal')
    doc.text(card.label.toUpperCase(), x + cardW / 2, y + 7, { align: 'center' })
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text(card.value, x + cardW / 2, y + 15, { align: 'center' })
  })
  y += 28

  // ── B. Analytics Charts ─────────────────────────────────────────────────────
  doc.setTextColor(15, 118, 110)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('B.  Analytics Charts', margin, y)
  doc.setDrawColor(15, 118, 110)
  doc.setLineWidth(0.5)
  doc.line(margin, y + 2, pageW - margin, y + 2)
  y += 8

  const chartLabels = ['Companies (This Week)', 'Revenue (This Year)', 'Top Plans']
  const chartImgW = pageW - margin * 2
  const chartImgH = 60

  for (let ci = 0; ci < chartRefs.length; ci++) {
    const imgData = await captureChart(chartRefs[ci])
    if (imgData) {
      // Chart title
      doc.setTextColor(51, 65, 85)
      doc.setFontSize(8)
      doc.setFont('helvetica', 'bold')
      doc.text(chartLabels[ci], margin, y + 4)
      y += 6

      // Check page space
      if (y + chartImgH > doc.internal.pageSize.getHeight() - 20) {
        doc.addPage()
        y = 16
      }

      doc.setDrawColor(226, 232, 240)
      doc.setLineWidth(0.3)
      doc.roundedRect(margin, y, chartImgW, chartImgH, 2, 2)
      doc.addImage(imgData, 'PNG', margin + 1, y + 1, chartImgW - 2, chartImgH - 2)
      y += chartImgH + 8
    }
  }

  // ── C. Recent Transactions ──────────────────────────────────────────────────
  if (y + 30 > doc.internal.pageSize.getHeight() - 20) { doc.addPage(); y = 16 }

  doc.setTextColor(15, 118, 110)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('C.  Recent Transactions', margin, y)
  doc.setDrawColor(15, 118, 110)
  doc.line(margin, y + 2, pageW - margin, y + 2)
  y += 6

  autoTable(doc, {
    startY: y,
    head: [['Transaction ID', 'Company Name', 'Plan', 'Amount', 'Date']],
    body: recentTransactions.length
      ? recentTransactions.map((tx) => [tx.code, tx.name, tx.plan, `$${tx.amount}`, tx.date])
      : [['—', 'No transactions available', '', '', '']],
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: [15, 118, 110], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [241, 245, 249] },
    margin: { left: margin, right: margin },
    tableLineColor: [226, 232, 240],
    tableLineWidth: 0.2,
  })
  y = doc.lastAutoTable.finalY + 10

  // ── D. Recently Registered Organizations ────────────────────────────────────
  if (y + 30 > doc.internal.pageSize.getHeight() - 20) { doc.addPage(); y = 16 }

  doc.setTextColor(15, 118, 110)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('D.  Recently Registered Organizations', margin, y)
  doc.setDrawColor(15, 118, 110)
  doc.line(margin, y + 2, pageW - margin, y + 2)
  y += 6

  autoTable(doc, {
    startY: y,
    head: [['Organization Name', 'Plan', 'Total Users', 'Registration Date', 'Status']],
    body: recentlyRegistered.length
      ? recentlyRegistered.map((org) => [
        org.organizationName || '-',
        org.planName || '-',
        String(org.totalUsers || 0),
        org.createdAt || '-',
        org.status || '-',
      ])
      : [['—', 'No organizations available', '', '', '']],
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [241, 245, 249] },
    margin: { left: margin, right: margin },
    tableLineColor: [226, 232, 240],
    tableLineWidth: 0.2,
  })
  y = doc.lastAutoTable.finalY + 10

  // ── E. Recent Plan Expired ──────────────────────────────────────────────────
  if (y + 30 > doc.internal.pageSize.getHeight() - 20) { doc.addPage(); y = 16 }

  doc.setTextColor(15, 118, 110)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('E.  Recent Plan Expired', margin, y)
  doc.setDrawColor(15, 118, 110)
  doc.line(margin, y + 2, pageW - margin, y + 2)
  y += 6

  autoTable(doc, {
    startY: y,
    head: [['Organization Name', 'Plan Name', 'Expiry Date', 'Status']],
    body: recentPlanExpired.length
      ? recentPlanExpired.map((t) => [t.name || '-', t.plan || '-', t.expiredOn || '-', 'Expired'])
      : [['—', 'No expired plans', '', '']],
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: [220, 38, 38], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [254, 242, 242] },
    columnStyles: { 3: { textColor: [220, 38, 38], fontStyle: 'bold' } },
    margin: { left: margin, right: margin },
    tableLineColor: [226, 232, 240],
    tableLineWidth: 0.2,
  })

  // ── Footer & Page Numbers ───────────────────────────────────────────────────
  addPageNumber(doc)

  doc.save(`superadmin-dashboard-report-${now.toISOString().slice(0, 10)}.pdf`)
}

function generateCSV({ stats, recentTransactions, recentlyRegistered, recentPlanExpired }) {
  const rows = []

  // ── Section: Report Header ───────────────────────────────────────────────────
  rows.push(['SUPERADMIN DASHBOARD REPORT'])
  rows.push([`Report Generated On:`, new Date().toLocaleString('en-GB', {
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit', second: '2-digit',
  })])
  rows.push([])

  // ── Section: Dashboard Summary ───────────────────────────────────────────────
  rows.push(['=== DASHBOARD SUMMARY ==='])
  rows.push(['Metric', 'Value'])
  rows.push(['Total Companies', stats.totalCompanies])
  rows.push(['Active Companies', stats.activeCompanies])
  rows.push(['Total Subscribers', stats.totalSubscribers])
  rows.push(['Total Earnings', `$${Number(stats.totalEarnings).toLocaleString()}`])
  rows.push([])

  // ── Section: Recent Transactions ─────────────────────────────────────────────
  rows.push(['=== RECENT TRANSACTIONS ==='])
  rows.push(['Transaction ID', 'Company Name', 'Plan', 'Amount', 'Transaction Date'])
  if (recentTransactions.length) {
    recentTransactions.forEach((tx) =>
      rows.push([
        tx.code || '-',
        tx.name || '-',
        tx.plan || '-',
        `$${tx.amount ?? 0}`,
        tx.date || '-',          // Transaction Date (formatted via formatDate)
      ])
    )
  } else {
    rows.push(['No transactions available', '', '', '', ''])
  }
  rows.push([])

  // ── Section: Recently Registered Organizations ───────────────────────────────
  rows.push(['=== RECENTLY REGISTERED ORGANIZATIONS ==='])
  rows.push(['Organization Name', 'Plan', 'Total Users', 'Registration Date', 'Status'])
  if (recentlyRegistered.length) {
    recentlyRegistered.forEach((org) =>
      rows.push([
        org.organizationName || '-',
        org.planName || '-',
        org.totalUsers ?? 0,
        org.createdAt || '-',    // Registration Date (formatted via formatDate)
        org.status || '-',
      ])
    )
  } else {
    rows.push(['No organizations available', '', '', '', ''])
  }
  rows.push([])

  // ── Section: Recent Plan Expired ─────────────────────────────────────────────
  rows.push(['=== RECENT PLAN EXPIRED ==='])
  rows.push(['Organization Name', 'Plan Name', 'Expiry Date', 'Status'])
  if (recentPlanExpired.length) {
    recentPlanExpired.forEach((t) =>
      rows.push([
        t.name || '-',
        t.plan || '-',
        t.expiredOn || '-',      // Expiry Date (formatted via formatDate)
        'Expired',
      ])
    )
  } else {
    rows.push(['No expired plans', '', '', ''])
  }

  const csvContent = rows
    .map((row) => row.map((cell) => `"${String(cell ?? '').replace(/"/g, '""')}"`).join(','))
    .join('\r\n')

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `superadmin-dashboard-${new Date().toISOString().slice(0, 10)}.csv`
  link.click()
  URL.revokeObjectURL(url)
}

// ─── Export Dropdown ───────────────────────────────────────────────────────────
function ExportDropdown({ onExportPDF, onExportCSV, exporting }) {
  const [open, setOpen] = useState(false)
  const ref = useRef(null)

  useEffect(() => {
    function handle(e) {
      if (ref.current && !ref.current.contains(e.target)) setOpen(false)
    }
    document.addEventListener('mousedown', handle)
    return () => document.removeEventListener('mousedown', handle)
  }, [])

  return (
    <div ref={ref} className="relative">
      <button
        type="button"
        disabled={exporting}
        onClick={() => setOpen((p) => !p)}
        className="inline-flex h-9 items-center gap-2 rounded-none border border-slate-200 bg-white px-3 text-sm font-medium text-slate-700 shadow-sm hover:bg-slate-50 disabled:opacity-60 disabled:cursor-not-allowed transition-colors"
      >
        {exporting ? (
          <svg className="h-4 w-4 animate-spin text-slate-500" viewBox="0 0 24 24" fill="none">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8z" />
          </svg>
        ) : (
          <HiArrowDownTray className="h-4 w-4" />
        )}
        {exporting ? 'Exporting…' : 'Export'}
        <HiChevronDown className={`h-3.5 w-3.5 transition-transform duration-200 ${open ? 'rotate-180' : ''}`} />
      </button>

      {open && !exporting && (
        <div
          className="absolute right-0 top-full z-50 mt-1.5 w-44 rounded-md border border-slate-200 bg-white py-1 shadow-xl ring-1 ring-black/5 animate-in fade-in slide-in-from-top-1 duration-150"
        >
          <button
            type="button"
            onClick={() => { setOpen(false); onExportPDF() }}
            className="flex w-full items-center gap-2.5 px-4 py-2.5 text-left text-sm text-gray-700 hover:bg-gray-50"
          >
            <span className="w-8 rounded bg-red-50 px-1 py-0.5 text-center text-[10px] font-bold text-red-600">PDF</span>
            PDF
          </button>
          <button
            type="button"
            onClick={() => { setOpen(false); onExportCSV() }}
            className="flex w-full items-center gap-2.5 px-4 py-2.5 text-left text-sm text-gray-700 hover:bg-gray-50"
          >
            <span className="w-8 rounded bg-green-50 px-1 py-0.5 text-center text-[10px] font-bold text-green-700">XLS</span>
            Excel
          </button>
        </div>
      )}
    </div>
  )
}

// ─── Main Dashboard ────────────────────────────────────────────────────────────
export default function SuperAdminDashboard() {
  const navigate = useNavigate()
  const [loading, setLoading] = useState(true)
  const [exporting, setExporting] = useState(false)

  const [stats, setStats] = useState({
    totalCompanies: 0,
    activeCompanies: 0,
    totalSubscribers: 0,
    totalEarnings: 0,
  })
  const [weeklyCompanies, setWeeklyCompanies] = useState(weekOrder.map((d) => ({ day: d, companies: 0 })))
  const [revenueData, setRevenueData] = useState(monthOrder.map((m) => ({ month: m, amount: 0 })))
  const [topPlans, setTopPlans] = useState([
    { name: 'Basic', value: 0, color: '#f97316' },
    { name: 'Premium', value: 0, color: '#3b82f6' },
    { name: 'Enterprise', value: 0, color: '#facc15' },
  ])
  const [recentTransactions, setRecentTransactions] = useState([])
  const [recentlyRegistered, setRecentlyRegistered] = useState([])
  const [recentPlanExpired, setRecentPlanExpired] = useState([])

  // Refs for chart capture
  const chartRef1 = useRef(null)
  const chartRef2 = useRef(null)
  const chartRef3 = useRef(null)

  const load = async () => {
    setLoading(true)
    try {
      const [tenantsRes, paymentsRes, paymentStatsRes] = await Promise.all([
        superadminService.getTenants(),
        superadminService.getPayments({ page: 1, limit: 200 }),
        superadminService.getPaymentStats(),
      ])

      const tenants = tenantsRes?.data?.data?.tenants || []
      const payments = paymentsRes?.data?.data?.payments || []
      const paymentStats = paymentStatsRes?.data?.data || {}

      const activeCompanies = tenants.filter((t) => String(t.status || '').toLowerCase() === 'active').length
      const totalEarnings =
        toNumber(paymentStats.total_revenue) ||
        toNumber(paymentStats.monthly_revenue) ||
        payments.reduce((sum, p) => sum + toNumber(p.amount), 0)

      setStats({
        totalCompanies: tenants.length,
        activeCompanies,
        totalSubscribers: payments.length,
        totalEarnings,
      })

      // Weekly company registration bars
      const dayCounts = { SUN: 0, MON: 0, TUE: 0, WED: 0, THU: 0, FRI: 0, SAT: 0 }
      tenants.forEach((t) => {
        if (!t.created_at) return
        const d = new Date(t.created_at)
        if (Number.isNaN(d.getTime())) return
        const key = weekOrder[d.getDay()]
        dayCounts[key] += 1
      })
      setWeeklyCompanies(weekOrder.map((day) => ({ day, companies: dayCounts[day] || 0 })))

      // Monthly revenue bars
      const monthRevenue = {}
      payments.forEach((p) => {
        if (!p.created_at) return
        const month = new Date(p.created_at).toLocaleString('en-US', { month: 'short' })
        monthRevenue[month] = (monthRevenue[month] || 0) + toNumber(p.amount)
      })
      setRevenueData(monthOrder.map((month) => ({ month, amount: monthRevenue[month] || 0 })))

      // Top plans donut
      const planCounts = { Basic: 0, Premium: 0, Enterprise: 0 }
      tenants.forEach((t) => {
        const plan = String(t.plan || t.plan_name || '').toLowerCase()
        if (plan.includes('enterprise')) planCounts.Enterprise += 1
        else if (plan.includes('premium')) planCounts.Premium += 1
        else planCounts.Basic += 1
      })
      setTopPlans([
        { name: 'Basic', value: planCounts.Basic, color: '#f97316' },
        { name: 'Premium', value: planCounts.Premium, color: '#3b82f6' },
        { name: 'Enterprise', value: planCounts.Enterprise, color: '#facc15' },
      ])

      setRecentTransactions(
        payments.slice(0, 6).map((p) => ({
          id: p.id,
          name: p.customer_name || p.tenant_name || `Tenant #${p.tenant_id || p.id}`,
          code: `#${p.invoice_no || p.id}`,
          date: formatDate(p.created_at),
          amount: toNumber(p.amount),
          plan: cap(p.plan_name || p.plan || p.billing_cycle || 'Subscription'),
        })),
      )

      setRecentlyRegistered(
        tenants.slice(0, 6).map((t) => ({
          id: t.id,
          organizationName: t.organizationName || t.name,
          tenantSlug: t.tenantSlug || t.slug || t.domain || t.subdomain || t.db_name || '-',
          planName: cap(t.planName || t.plan || t.plan_name || 'Basic'),
          totalUsers: t.totalUsers || 0,
          status: cap(t.status || 'Active'),
          createdAt: formatDate(t.createdAt || t.created_at),
          lastActivity: formatDate(t.lastActivity),
        })),
      )

      console.log(tenants)
      const now = new Date()
      const expired = tenants
        .filter((t) => {
          const status = String(t.status || '').toLowerCase()
          if (status.includes('expired')) return true
          const expiry = t.expires_at || t.expiry_date || t.plan_expiry
          if (!expiry) return false
          const d = new Date(expiry)
          return !Number.isNaN(d.getTime()) && d < now
        })
        .slice(0, 6)
        .map((t) => ({
          id: t.id,
          name: t.name,
          expiredOn: formatDate(t.expires_at || t.expiry_date || t.plan_expiry),
          plan: cap(t.plan || t.plan_name || 'Basic'),
        }))
      setRecentPlanExpired(expired)
    } catch (error) {
      console.error('Failed to load superadmin dashboard', error)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { load() }, [])

  const totalPlans = useMemo(
    () => topPlans.reduce((sum, p) => sum + p.value, 0),
    [topPlans],
  )

  // ── Export handlers ──────────────────────────────────────────────────────────
  const handleExportPDF = async () => {
    setExporting(true)
    const toastId = toast.loading('Generating PDF, please wait…')
    try {
      // Give charts 300ms to fully paint before capture
      await new Promise((r) => setTimeout(r, 300))
      await generatePDF({
        stats,
        recentTransactions,
        recentlyRegistered,
        recentPlanExpired,
        chartRefs: [chartRef1, chartRef2, chartRef3],
      })
      toast.success('PDF downloaded successfully!', { id: toastId })
    } catch (err) {
      console.error('PDF export failed', err)
      toast.error('PDF export failed. Please try again.', { id: toastId })
    } finally {
      setExporting(false)
    }
  }

  const handleExportCSV = () => {
    setExporting(true)
    const toastId = toast.loading('Generating CSV…')
    try {
      generateCSV({ stats, recentTransactions, recentlyRegistered, recentPlanExpired })
      toast.success('CSV downloaded successfully!', { id: toastId })
    } catch (err) {
      console.error('CSV export failed', err)
      toast.error('CSV export failed. Please try again.', { id: toastId })
    } finally {
      setExporting(false)
    }
  }

  // ─────────────────────────────────────────────────────────────────────────────

  return (
    <div className="space-y-6 pb-12 animate-in fade-in duration-500 min-w-0">
      {/* Header */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Dashboard</h1>
          <p className="mt-1 text-xs text-slate-500">Super Admin / Dashboard</p>
        </div>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={load}
            className="inline-flex h-9 items-center gap-2 rounded-none border border-slate-200 bg-white px-3 text-sm font-medium text-slate-700 shadow-sm hover:bg-slate-50"
          >
            <HiArrowPath className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />
            Refresh
          </button>

          <ExportDropdown
            exporting={exporting}
            onExportPDF={handleExportPDF}
            onExportCSV={handleExportCSV}
          />
        </div>
      </div>

      {/* Welcome Banner */}
      <div className="rounded-none border border-slate-200 bg-gradient-to-r from-[#0F766E] to-[#0c6b64] p-5 text-white shadow-sm">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <p className="text-2xl font-bold">Welcome Back, Super Admin</p>
            <p className="mt-1 text-sm text-emerald-50">
              {stats.totalCompanies} companies tracked across the platform.
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button className="h-8 rounded-none bg-slate-900 px-4 text-xs font-semibold text-white">Companies</button>
            <button className="h-8 rounded-none bg-white px-4 text-xs font-semibold text-slate-900">All Packages</button>
          </div>
        </div>
      </div>

      {/* Metric Tiles */}
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <MetricTile icon={HiBuildingOffice} label="Total Companies" value={stats.totalCompanies} />
        <MetricTile icon={HiUsers} label="Active Companies" value={stats.activeCompanies} tone="blue" />
        <MetricTile icon={HiUsers} label="Total Subscribers" value={stats.totalSubscribers} tone="emerald" />
        <MetricTile icon={HiCurrencyDollar} label="Total Earnings" value={`$${stats.totalEarnings.toLocaleString()}`} tone="green" />
      </div>

      {/* Charts row 1 */}
      <div className="grid gap-4 lg:grid-cols-2">
        {/* Companies Chart */}
        <div ref={chartRef1} className="rounded-none border border-slate-200 bg-white p-4 shadow-sm">
          <div className="mb-3 flex items-center justify-between">
            <h3 className="text-sm font-semibold text-slate-900">Companies</h3>
            <span className="text-xs text-slate-400">This week</span>
          </div>
          <div className="h-56">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={weeklyCompanies}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#eef2f7" />
                <XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: '#64748b' }} />
                <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: '#64748b' }} />
                <ChartTooltip />
                <Bar dataKey="companies" radius={[6, 6, 0, 0]} fill="#111827" />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Revenue Chart */}
        <div ref={chartRef2} className="rounded-none border border-slate-200 bg-white p-4 shadow-sm">
          <div className="mb-3 flex items-center justify-between">
            <h3 className="text-sm font-semibold text-slate-900">Revenue</h3>
            <span className="text-xs text-slate-400">{new Date().getFullYear()}</span>
          </div>
          <div className="h-56">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={revenueData}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#eef2f7" />
                <XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: '#64748b' }} />
                <YAxis axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: '#64748b' }} />
                <ChartTooltip />
                <Bar dataKey="amount" radius={[4, 4, 0, 0]} fill="#3b82f6" />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* Top Plans chart */}
      <div ref={chartRef3} className="rounded-none border border-slate-200 bg-white p-4 shadow-sm">
        <div className="mb-3 flex items-center justify-between">
          <h3 className="text-sm font-semibold text-slate-900">Top Plans</h3>
          <span className="text-xs text-slate-400">This month</span>
        </div>
        <div className="grid gap-4 md:grid-cols-2">
          <div className="h-56">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie data={topPlans} dataKey="value" innerRadius={52} outerRadius={84} paddingAngle={2}>
                  {topPlans.map((p) => (
                    <Cell key={p.name} fill={p.color} />
                  ))}
                </Pie>
                <ChartTooltip />
              </PieChart>
            </ResponsiveContainer>
          </div>
          <div className="space-y-3 self-center">
            {topPlans.map((plan) => {
              const percent = totalPlans ? Math.round((plan.value / totalPlans) * 100) : 0
              return (
                <div key={plan.name} className="flex items-center justify-between border-b border-slate-100 py-1.5">
                  <div className="flex items-center gap-2">
                    <span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: plan.color }} />
                    <span className="text-sm text-slate-700">{plan.name}</span>
                  </div>
                  <span className="text-sm font-semibold text-slate-900">{percent}%</span>
                </div>
              )
            })}
          </div>
        </div>
      </div>

      {/* Recent Transactions */}
      <div className="rounded-none border border-slate-200 bg-white p-4 shadow-sm">
        <div className="mb-3 flex items-center justify-between">
          <h3 className="text-sm font-semibold text-slate-900">Recent Transactions</h3>
          <button
            type="button"
            onClick={() => navigate('/superadmin/billing')}
            className="text-xs font-medium text-slate-500 hover:text-slate-900"
          >
            View all
          </button>
        </div>
        <div className="space-y-3">
          {recentTransactions.length ? recentTransactions.map((tx) => (
            <div key={tx.id} className="flex items-center justify-between border-b border-slate-100 pb-3 last:border-b-0 last:pb-0">
              <div className="min-w-0">
                <p className="truncate text-sm font-semibold text-slate-900">{tx.name}</p>
                <p className="text-xs text-slate-500">{tx.code} • {tx.date}</p>
              </div>
              <div className="text-right">
                <p className="text-sm font-semibold text-emerald-600">+${tx.amount}</p>
                <p className="text-xs text-slate-500">{tx.plan}</p>
              </div>
            </div>
          )) : (
            <p className="text-sm text-slate-500">No transactions found.</p>
          )}
        </div>
      </div>

      {/* Recently Registered + Recent Plan Expired */}
      <div className="grid gap-4 lg:grid-cols-2">
        {/* Recently Registered */}
        <div className="rounded-none border border-slate-200 bg-white p-5 shadow-sm">
          <div className="mb-4 flex items-center justify-between">
            <div>
              <h3 className="text-base font-bold text-slate-900">Recently Registered Organizations</h3>
              <p className="text-xs text-slate-500 mt-0.5">Latest tenants joined the platform</p>
            </div>
            <button
              type="button"
              onClick={() => navigate('/superadmin/tenants')}
              className="text-xs font-medium text-slate-500 hover:text-slate-900"
            >
              View all
            </button>
          </div>
          <div className="space-y-4">
            {recentlyRegistered.length ? recentlyRegistered.map((organization) => (
              <div key={organization.id} className="flex flex-col lg:flex-row lg:items-center justify-between border-b border-slate-100 pb-4 last:border-b-0 last:pb-0 gap-4">
                <div className="flex-1 min-w-0">
                  <div className="flex flex-wrap items-center gap-2 mb-2">
                    <p className="truncate text-base font-bold text-slate-900">{organization.organizationName}</p>
                    <span className="text-[10px] font-semibold px-2 py-0.5 rounded bg-slate-100 text-slate-600 border border-slate-200 uppercase tracking-wide">
                      {organization.tenantSlug}
                    </span>
                    {organization.status === 'Active' ? (
                      <span className="text-[10px] font-semibold px-2 py-0.5 rounded bg-emerald-50 text-emerald-700 border border-emerald-200 uppercase tracking-wide">Active</span>
                    ) : (
                      <span className="text-[10px] font-semibold px-2 py-0.5 rounded bg-red-50 text-red-700 border border-red-200 uppercase tracking-wide">{organization.status}</span>
                    )}
                    <Badge
                      label={organization.planName}
                      color={organization.planName.toLowerCase().includes('enterprise') ? 'amber' : organization.planName.toLowerCase().includes('pro') ? 'emerald' : 'blue'}
                    />
                  </div>

                  <div className="flex flex-wrap items-center gap-x-5 gap-y-2 mt-3">
                    <div className="flex items-center gap-1.5 text-xs text-slate-600">
                      <HiCalendarDays className="w-4 h-4 text-slate-400" />
                      <span>Registered: <span className="font-medium text-slate-900">{organization.createdAt}</span></span>
                    </div>
                    <div className="flex items-center gap-1.5 text-xs text-slate-600">
                      <HiClock className="w-4 h-4 text-slate-400" />
                      <span>Last Activity: <span className="font-medium text-slate-900">{organization.lastActivity !== '-' ? organization.lastActivity : 'N/A'}</span></span>
                    </div>
                  </div>
                </div>

                <div className="flex flex-wrap lg:flex-nowrap items-center gap-3 shrink-0">
                  <div className="flex items-center gap-2 bg-slate-50 px-3 py-2 rounded-lg border border-slate-200">
                    <div className="w-8 h-8 rounded-full bg-slate-100 text-slate-600 flex items-center justify-center">
                      <HiUsers className="w-4 h-4" />
                    </div>
                    <div>
                      <p className="text-[10px] uppercase font-bold text-slate-600 tracking-wider">Total Users</p>
                      <p className="text-lg font-black text-slate-900 leading-none">{organization.totalUsers || 0}</p>
                    </div>
                  </div>
                </div>
              </div>
            )) : (
              <div className="py-8 text-center">
                <p className="text-sm text-slate-500">No recent registrations found.</p>
              </div>
            )}
          </div>
        </div>

        {/* Recent Plan Expired */}
        <div className="rounded-none border border-slate-200 bg-white p-4 shadow-sm">
          <div className="mb-3 flex items-center justify-between">
            <h3 className="text-sm font-semibold text-slate-900">Recent Plan Expired</h3>
            <button
              type="button"
              onClick={() => navigate('/superadmin/tenants')}
              className="text-xs font-medium text-slate-500 hover:text-slate-900"
            >
              Expired
            </button>
          </div>
          <div className="space-y-3">
            {recentPlanExpired.length ? recentPlanExpired.map((t) => (
              <div key={t.id} className="flex items-center justify-between border-b border-slate-100 pb-3 last:border-b-0 last:pb-0">
                <div className="min-w-0">
                  <p className="truncate text-sm font-semibold text-slate-900">{t.name}</p>
                  <p className="text-xs text-slate-500">Expired: {t.expiredOn}</p>
                </div>
                <button
                  type="button"
                  className="text-xs font-medium text-blue-600 hover:text-blue-700"
                >
                  Send Reminder
                </button>
              </div>
            )) : (
              <p className="text-sm text-slate-500">No expired plans.</p>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
